### ISSUE TITLE
#4 in Deploy.md states to run qtumproject/server-receive

### ISSUE THREAD

**Issue by denuoweb** [qtumproject/mobile-api-server#2]
Server-Receive is not available from Qtum. Could this be put online please?

**Comment by GiorgiSheklashvili** [comment]
@denuoweb  Hello, have you been able to run this project?

**Comment by denuoweb** [comment]
Yes

**Comment by GiorgiSheklashvili** [comment]
Can you tell me how did you run insight-api? Because this project needs insight-api.
There is qtuminfo-insight project but I was not able to run it.
